# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GisProgrammierungCSFTFFDialog
                                 A QGIS plugin
 Das Plugin analysiert DGMs und reale Punktwolken auf folgende geometrischen Alogrithmen: "Konvexe Hülle", "Punkt-in-Polygon-Test" und dem "Ear-Clipping-Algorithmus". Die Ergebnisse werden visualisert und einem Performancevergleich (m/s) unterzogen. Hierbei wird eine große Anzahl von Geoobjekten (> 1.000.000) in eine relationale und Objektdatenbank gespeichert und eingelesen. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-01-04
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Czarnach Simone, Feicht Tamara, Folger Florian
        email                : czarnach@hm.edu, Klein6@hm.edu, ffolger@hm.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gis_programmierung_cs_ft_ff_dialog_base.ui'))


class GisProgrammierungCSFTFFDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GisProgrammierungCSFTFFDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
